language: elixir
elixir:
  - 1.7.2
otp_release:
  - 21.0.5

sudo: required

cache:
  directories:
    - _build
    - deps

before_script:
  - mix local.hex --force
  - mix deps.get --only test
  - mix deps.clean --unused
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=test travis_wait 40 mix dialyzer --plt

script:
  - mix test
  - mix credo --strict
  - mix format --check-formatted
  - MIX_ENV=test mix dialyzer --format short --halt-exit-status
